In [1]:
import numpy as np

ITERATION_LIMIT = 1000

# 3x3 matrix 
n = 3

# initialize the matrix
A = np.random.uniform(-10,10, size=(n,n))
A = A.round(4)
# initialize the RHS vector
b = np.random.uniform(-10,10, size=n)
b = b.round(4)


In [2]:
def GenerateDignoalMat():
    ret = A.copy()
    rowsum = np.sum(np.absolute(A), axis = 0)
    colsum = np.sum(np.absolute(A), axis = 1)
    for i in range(n):
        ret[i][i] = rowsum[i] - abs(A[i][i])
    for i in range(n):
        tmp = colsum[i] - abs(A[i][i])
        if(tmp > ret[i][i]):
            ret[i][i] = tmp
        
    return ret

In [3]:
# A1 Random

# initialize the matrix
A1 = np.random.uniform(-10,10, size=(n,n))
A1 = A.round(4)
# initialize the RHS vector
b1 = np.random.uniform(-10,10, size=n)
b1 = b.round(4)

In [4]:
diagonalMat = GenerateDignoalMat()

In [5]:

# Jacobi

def GaussJacobi(A, b):

    # prints the system
    print("System:")
    for i in range(A.shape[0]):
        row = ["{}*x{}".format(A[i, j], j + 1) for j in range(A.shape[1])]
        print(" + ".join(row), "=", b[i])
    print()

    x = np.zeros_like(b)
    for it_count in range(ITERATION_LIMIT):
        #if it_count != 0:
        print("Iteration {0}: {1}".format(it_count, x))
        x_new = np.zeros_like(x)

        for i in range(A.shape[0]):
            s1 = np.dot(A[i, :i], x[:i])
            s2 = np.dot(A[i, i + 1:], x[i + 1:])
            x_new[i] = (b[i] - s1 - s2) / A[i, i]
            if x_new[i] == x_new[i-1]:
              break

        if np.allclose(x, x_new, rtol=1e-2):
            break

        x = x_new

    print("Solution:")
    print(x)
    error = np.dot(A, x) - b
    print("Error:")
    print(error)


In [6]:

def GaussSeidel(A, b):

    print("**System of equations:**")
    for i in range(A.shape[0]):
        row = ["{0:3g}*x{1}".format(A[i, j], j + 1) for j in range(A.shape[1])]
        print("[{0}] = [{1:3g}]".format(" + ".join(row), b[i]))

    x = np.zeros_like(b)
    for it_count in range(1, ITERATION_LIMIT):
        x_new = np.zeros_like(x)
        print("Iteration {0}: {1}".format(it_count, x))
        for i in range(A.shape[0]):
            s1 = np.dot(A[i, :i], x_new[:i])
            s2 = np.dot(A[i, i + 1 :], x[i + 1 :])
            x_new[i] = (b[i] - s1 - s2) / A[i, i]
        if np.allclose(x, x_new, rtol=1e-2):
            break
        x = x_new

    print("Solution: {0}".format(x))
    error = np.dot(A, x) - b
    print("Error: {0}".format(error))



## Input diagonal matrix

In [7]:
diagonalMat

array([[15.252 , -6.8043, -6.4872],
       [-5.4692, 16.3175,  3.9333],
       [ 9.7828,  9.5132, 19.296 ]])

### Gauss Seidel

In [8]:
GaussSeidel(diagonalMat, b)

**System of equations:**
[15.252*x1 + -6.8043*x2 + -6.4872*x3] = [7.3083]
[-5.4692*x1 + 16.3175*x2 + 3.9333*x3] = [-7.1684]
[9.7828*x1 + 9.5132*x2 + 19.296*x3] = [-5.1095]
Iteration 1: [0. 0. 0.]
Iteration 2: [ 0.47916994 -0.27870224 -0.37032409]
Iteration 3: [ 0.19732231 -0.28390434 -0.2248666 ]
Iteration 4: [ 0.2568696  -0.29900787 -0.24760998]
Iteration 5: [ 0.24045799 -0.29902637 -0.23928041]
Iteration 6: [ 0.24399259 -0.29984949 -0.24066659]
Solution: [ 0.24399259 -0.29984949 -0.24066659]
Error: [ 1.45932049e-02 -5.45227413e-03 -8.88178420e-16]


### Non diagnoal matrix

In [9]:
print(A1)

[[-6.4875 -6.8043 -6.4872]
 [-5.4692  8.1046  3.9333]
 [ 9.7828  9.5132  3.2497]]


In [10]:
print(b1)

[ 7.3083 -7.1684 -5.1095]


In [11]:
GaussSeidel(A1,b1)

**System of equations:**
[-6.4875*x1 + -6.8043*x2 + -6.4872*x3] = [7.3083]
[-5.4692*x1 + 8.1046*x2 + 3.9333*x3] = [-7.1684]
[9.7828*x1 + 9.5132*x2 + 3.2497*x3] = [-5.1095]
Iteration 1: [0. 0. 0.]
Iteration 2: [-1.12652023 -1.64469122  6.63362729]
Iteration 3: [-6.03483538 -8.17636501 40.53035148]
Iteration 4: [-33.07936118 -42.87738736 223.52845986]
Iteration 5: [-179.67345171 -230.61507456 1214.4158755 ]
Iteration 6: [ -973.60968259 -1247.27888349  6580.64829898]
Iteration 7: [-5273.28404443 -6753.13740964 35642.15787773]
Iteration 8: [-28558.72709179 -36570.81881781 193028.50092967]
Iteration 9: [-154664.04270504 -198052.31022741 1045374.50384042]
Iteration 10: [ -837603.61543479 -1072576.11700657  5661364.02002721]
Iteration 11: [-4536150.79862392 -5808672.38558435 30659849.54359452]
Iteration 12: [-2.45661092e+07 -3.14576115e+07  1.66042366e+08]
Iteration 13: [-1.33040928e+08 -1.70362743e+08  8.99223817e+08]
Iteration 14: [-7.20500275e+08 -9.22621369e+08  4.86986236e+09]
Iteration 

Iteration 295: [-1.03031689e+215 -1.31935048e+215  6.96391331e+215]
Iteration 296: [-5.57981379e+215 -7.14511238e+215  3.77139691e+216]
Iteration 297: [-3.02181999e+216 -3.86952760e+216  2.04244855e+217]
Iteration 298: [-1.63650552e+217 -2.09559249e+217  1.10611431e+218]
Iteration 299: [-8.86270636e+217 -1.13489509e+218  5.99030445e+218]
Iteration 300: [-4.79971273e+218 -6.14617049e+218  3.24412650e+219]
Iteration 301: [-2.59934623e+219 -3.32853776e+219  1.75689847e+220]
Iteration 302: [-1.40770942e+220 -1.80261248e+220  9.51470988e+220]
Iteration 303: [-7.62363158e+220 -9.76227996e+220  5.15281364e+221]
Iteration 304: [-4.12867583e+221 -5.28688840e+221  2.79057257e+222]
Iteration 305: [-2.23593755e+222 -2.86318248e+222  1.51127050e+223]
Iteration 306: [-1.21090077e+223 -1.55059334e+223  8.18447997e+223]
Iteration 307: [-6.55778902e+223 -8.39743785e+223  4.43241050e+224]
Iteration 308: [-3.55145507e+224 -4.54774058e+224  2.40042897e+225]
Iteration 309: [-1.92333622e+225 -2.46288746e+22

Iteration 533: [nan nan nan]
Iteration 534: [nan nan nan]
Iteration 535: [nan nan nan]
Iteration 536: [nan nan nan]
Iteration 537: [nan nan nan]
Iteration 538: [nan nan nan]
Iteration 539: [nan nan nan]
Iteration 540: [nan nan nan]
Iteration 541: [nan nan nan]
Iteration 542: [nan nan nan]
Iteration 543: [nan nan nan]
Iteration 544: [nan nan nan]
Iteration 545: [nan nan nan]
Iteration 546: [nan nan nan]
Iteration 547: [nan nan nan]
Iteration 548: [nan nan nan]
Iteration 549: [nan nan nan]
Iteration 550: [nan nan nan]
Iteration 551: [nan nan nan]
Iteration 552: [nan nan nan]
Iteration 553: [nan nan nan]
Iteration 554: [nan nan nan]
Iteration 555: [nan nan nan]
Iteration 556: [nan nan nan]
Iteration 557: [nan nan nan]
Iteration 558: [nan nan nan]
Iteration 559: [nan nan nan]
Iteration 560: [nan nan nan]
Iteration 561: [nan nan nan]
Iteration 562: [nan nan nan]
Iteration 563: [nan nan nan]
Iteration 564: [nan nan nan]
Iteration 565: [nan nan nan]
Iteration 566: [nan nan nan]
Iteration 567:

Iteration 907: [nan nan nan]
Iteration 908: [nan nan nan]
Iteration 909: [nan nan nan]
Iteration 910: [nan nan nan]
Iteration 911: [nan nan nan]
Iteration 912: [nan nan nan]
Iteration 913: [nan nan nan]
Iteration 914: [nan nan nan]
Iteration 915: [nan nan nan]
Iteration 916: [nan nan nan]
Iteration 917: [nan nan nan]
Iteration 918: [nan nan nan]
Iteration 919: [nan nan nan]
Iteration 920: [nan nan nan]
Iteration 921: [nan nan nan]
Iteration 922: [nan nan nan]
Iteration 923: [nan nan nan]
Iteration 924: [nan nan nan]
Iteration 925: [nan nan nan]
Iteration 926: [nan nan nan]
Iteration 927: [nan nan nan]
Iteration 928: [nan nan nan]
Iteration 929: [nan nan nan]
Iteration 930: [nan nan nan]
Iteration 931: [nan nan nan]
Iteration 932: [nan nan nan]
Iteration 933: [nan nan nan]
Iteration 934: [nan nan nan]
Iteration 935: [nan nan nan]
Iteration 936: [nan nan nan]
Iteration 937: [nan nan nan]
Iteration 938: [nan nan nan]
Iteration 939: [nan nan nan]
Iteration 940: [nan nan nan]
Iteration 941:

### Gauss Jacobi

#### Diagnoal matrix

In [12]:
GaussJacobi(diagonalMat, b)

System:
15.251999999999999*x1 + -6.8043*x2 + -6.4872*x3 = 7.3083
-5.4692*x1 + 16.317500000000003*x2 + 3.9333*x3 = -7.1684
9.7828*x1 + 9.5132*x2 + 19.296*x3 = -5.1095

Iteration 0: [0. 0. 0.]
Iteration 1: [ 0.47916994 -0.43930749 -0.26479581]
Iteration 2: [ 0.17055708 -0.21487375 -0.29114343]
Iteration 3: [ 0.25947606 -0.31196168 -0.24533006]
Iteration 4: [ 0.2356487  -0.29320158 -0.24254501]
Iteration 5: [ 0.24520263 -0.30185922 -0.23971387]
Iteration 6: [ 0.24254442 -0.29933943 -0.24028924]
Solution:
[ 0.24254442 -0.29933943 -0.24028924]
Error:
[-0.01341285  0.01227518 -0.00203349]


#### Random matrix

In [13]:
GaussJacobi(A1, b1)

System:
-6.4875*x1 + -6.8043*x2 + -6.4872*x3 = 7.3083
-5.4692*x1 + 8.1046*x2 + 3.9333*x3 = -7.1684
9.7828*x1 + 9.5132*x2 + 3.2497*x3 = -5.1095

Iteration 0: [0. 0. 0.]
Iteration 1: [-1.12652023 -0.88448535 -1.57229898]
Iteration 2: [ 1.37338291 -0.88162782  4.40819404]
Iteration 3: [-4.60983063 -2.0970614  -3.12580501]
Iteration 4: [ 4.19860611 -2.47831563 18.44395346]
Iteration 5: [-16.97028314  -7.0023179   -6.95661496]
Iteration 6: [13.17403071 -8.96032117 70.01318169]
Iteration 7: [-61.73858943 -25.97288439 -15.00048628]
Iteration 8: [ 41.11447427 -35.26733961 260.31695739]
Iteration 9: [-224.44191245  -99.47558249  -22.10017036]
Iteration 10: [ 125.30583909 -141.61827943  965.28662721]
Iteration 11: [-817.83467427 -384.794758     35.78531964]
Iteration 12: [ 366.67501291 -570.14833529 3586.86433923]
Iteration 13: [-2989.83496317 -1494.20858831   563.65736129]
Iteration 14: [ 1002.41651843 -2292.05726128 13373.0969382 ]
Iteration 15: [-10969.62119994  -5814.6181384    3690.57122859

Iteration 155: [-2.53478030e+45 -2.81125287e+45  7.98204809e+45]
Iteration 156: [-5.03314596e+45 -5.58436075e+45  1.58603131e+46]
Iteration 157: [-1.00025214e+46 -1.10937803e+46  3.14993387e+46]
Iteration 158: [-1.98623663e+46 -2.20371319e+46  6.25873208e+46]
Iteration 159: [-3.94711694e+46 -4.37783435e+46  1.24304766e+47]
Iteration 160: [-7.83828745e+46 -8.69634106e+46  2.46979934e+47]
Iteration 161: [-1.55758473e+47 -1.72758408e+47  4.90538912e+47]
Iteration 162: [-3.09321618e+47 -3.43176831e+47  9.74625129e+47]
Iteration 163: [-6.14645090e+47 -6.81740593e+47  1.93579141e+48]
Iteration 164: [-1.22067029e+48 -1.35425132e+48  3.84604259e+48]
Iteration 165: [-2.42548211e+48 -2.69029061e+48  7.63911655e+48]
Iteration 166: [-4.81709942e+48 -5.34417292e+48  1.51771791e+49]
Iteration 167: [-9.57133574e+48 -1.06164498e+49  3.01458307e+49]
Iteration 168: [-1.90095605e+49 -2.10892759e+49  5.98919510e+49]
Iteration 169: [-3.77700662e+49 -4.18947387e+49  1.18962744e+50]
Iteration 170: [-7.501668

Iteration 359: [-1.63782962e+106 -1.81684625e+106  5.15936745e+106]
Iteration 360: [-3.25356170e+106 -3.60917969e+106  1.02491249e+107]
Iteration 361: [-6.46322651e+106 -7.16966449e+106  2.03599691e+107]
Iteration 362: [-1.28392514e+107 -1.42425962e+107  4.04452425e+107]
Iteration 363: [-2.55052763e+107 -2.82930319e+107  8.03447995e+107]
Iteration 364: [-5.06664364e+107 -5.62043354e+107  1.59605591e+108]
Iteration 365: [-1.00649284e+108 -1.11650364e+108  3.17057789e+108]
Iteration 366: [-1.99940611e+108 -2.21794347e+108  6.29837849e+108]
Iteration 367: [-3.97183633e+108 -4.40596254e+108  1.25117795e+109]
Iteration 368: [-7.89008481e+108 -8.75248003e+108  2.48547507e+109]
Iteration 369: [-1.56737170e+109 -1.73868720e+109  4.93741622e+109]
Iteration 370: [-3.11359648e+109 -3.45391611e+109  9.80821704e+109]
Iteration 371: [-6.18518446e+109 -6.86123213e+109  1.94841020e+110]
Iteration 372: [-1.22869187e+110 -1.36298928e+110  3.87053254e+110]
Iteration 373: [-2.44080628e+110 -2.70758917e+11

Iteration 511: [-3.34193944e+151 -3.70721721e+151  1.05275258e+152]
Iteration 512: [-6.63878958e+151 -7.36441681e+151  2.09130147e+152]
Iteration 513: [-1.31880089e+152 -1.46294732e+152  4.15438719e+152]
Iteration 514: [-2.61980858e+152 -2.90615662e+152  8.25272358e+152]
Iteration 515: [-5.20427081e+152 -5.77310351e+152  1.63941018e+153]
Iteration 516: [-1.03383258e+153 -1.14683166e+153  3.25670150e+153]
Iteration 517: [-2.05371674e+153 -2.27819031e+153  6.46946374e+153]
Iteration 518: [-4.07972483e+153 -4.52564338e+153  1.28516418e+154]
Iteration 519: [-8.10440619e+153 -8.99022697e+153  2.55298897e+154]
Iteration 520: [-1.60994681e+154 -1.78591582e+154  5.07153313e+154]
Iteration 521: [-3.19817229e+154 -3.54773614e+154  1.00746414e+155]
Iteration 522: [-6.35319497e+154 -7.04760639e+154  2.00133561e+155]
Iteration 523: [-1.26206729e+155 -1.40001268e+155  3.97566929e+155]
Iteration 524: [-2.50710683e+155 -2.78113645e+155  7.89769902e+155]
Iteration 525: [-4.98038788e+155 -5.52474992e+15

Iteration 679: [-4.01027061e+201 -4.44859773e+201  1.26328523e+202]
Iteration 680: [-7.96643482e+201 -8.83717518e+201  2.50952627e+202]
Iteration 681: [-1.58253868e+202 -1.75551196e+202  4.98519412e+202]
Iteration 682: [-3.14372583e+202 -3.48733863e+202  9.90312823e+202]
Iteration 683: [-6.24503664e+202 -6.92762623e+202  1.96726439e+203]
Iteration 684: [-1.24058155e+203 -1.37617852e+203  3.90798653e+203]
Iteration 685: [-2.46442523e+203 -2.73378971e+203  7.76324668e+203]
Iteration 686: [-4.89560055e+203 -5.43069524e+203  1.54217520e+204]
Iteration 687: [-9.72514988e+203 -1.07881198e+204  3.06354344e+204]
Iteration 688: [-1.93190885e+204 -2.14306867e+204  6.08575368e+204]
Iteration 689: [-3.83775246e+204 -4.25722316e+204  1.20893986e+205]
Iteration 690: [-7.62372614e+204 -8.45700805e+204  2.40156876e+205]
Iteration 691: [-1.51445933e+205 -1.67999145e+205  4.77073567e+205]
Iteration 692: [-3.00848564e+205 -3.33731653e+205  9.47710478e+205]
Iteration 693: [-5.97638093e+205 -6.62960614e+20

Iteration 896: [-1.94435184e+266 -2.15687170e+266  6.12495065e+266]
Iteration 897: [-3.86247056e+266 -4.28464297e+266  1.21672637e+267]
Iteration 898: [-7.67282884e+266 -8.51147774e+266  2.41703673e+267]
Iteration 899: [-1.52421362e+267 -1.69081190e+267  4.80146290e+267]
Iteration 900: [-3.02786262e+267 -3.35881144e+267  9.53814468e+267]
Iteration 901: [-6.01487345e+267 -6.67230594e+267  1.89476011e+268]
Iteration 902: [-1.19485945e+268 -1.32545894e+268  3.76395621e+268]
Iteration 903: [-2.37359791e+268 -2.63303485e+268  7.47712928e+268]
Iteration 904: [-4.71517134e+268 -5.23054491e+268  1.48533775e+269]
Iteration 905: [-9.36672579e+268 -1.03905195e+269  2.95063538e+269]
Iteration 906: [-1.86070761e+269 -2.06408506e+269  5.86146092e+269]
Iteration 907: [-3.69631064e+269 -4.10032158e+269  1.16438393e+270]
Iteration 908: [-7.34275082e+269 -8.14532181e+269  2.31305804e+270]
Iteration 909: [-1.45864336e+270 -1.61807473e+270  4.59490840e+270]
Iteration 910: [-2.89760676e+270 -3.21431847e+27